#!/bin/bash

cd /usr/share/lcc

LoopCounter=0

while [ true ]; do
  ScriptStart=$(date +%s)

  ./logic-processor.php

  LoopCounter=$((LoopCounter + 1))
  if [ $LoopCounter -eq 6 ]; then
    ./scheduler.php
    LoopCounter=0
  fi

  ScriptEnd=$(date +%s)

  Runtime=$(($ScriptEnd - $ScriptStart))
  echo "Script Runtime: $Runtime seconds"
  if [ $Runtime -lt 10 ]; then
    Delay=$((10 - $Runtime))
    echo "Sleeping $Delay seconds"
    sleep $Delay
  fi
done
