interface=wlan0
driver=nl80211
ssid=LCC-WLAN
hw_mode=g
channel=6                     # pick a quiet 1/6/11 channel
ieee80211n=0                  # explicitly no N
wmm_enabled=0
# Rate limiting for reliability near brushed motors
supported_rates=10 20 55 110 60 90 120 180 240
basic_rates=10 20 55 110
# or even stricter for lowest rates:
# supported_rates=10 20 55 110
# basic_rates=10 20

auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=1a2b3c4d5e

country_code=US
ieee80211d=1
macaddr_acl=0
ignore_broadcast_ssid=0
max_num_sta=32
logger_syslog=-1
logger_syslog_level=2
