# Interface
interface=wlan0
listen-address=127.0.0.1
listen-address=192.168.4.1
bind-interfaces
except-interface=eth0
except-interface=end0

# Do not serve DHCP on other interfaces
no-dhcp-interface=lo
no-dhcp-interface=eth0
no-dhcp-interface=end0

# Domain / DNS
domain=lcc.local
local=/lcc.local/
expand-hosts
no-resolv
no-poll

# DHCP
dhcp-range=192.168.4.50,192.168.4.200,255.255.255.0,12h
dhcp-option=option:router,192.168.4.1
dhcp-option=option:dns-server,192.168.4.1
dhcp-authoritative
dhcp-ignore-names
dhcp-generate-names

# Logging (helpful while debugging)
log-dhcp
log-queries
